!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.if_monthly.IFMonthlyLong {
        target_type: 'ASV',
        gain_range: [0, 10],
        which_set: 'train'
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.maxout.Maxout {
                     layer_name: 'h0',
                     num_units: 100,
                     num_pieces: 4,
                     irange: .005,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.maxout.Maxout {
                     layer_name: 'h1',
                     num_units: 100,
                     num_pieces: 4,
                     irange: .005,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.Linear {
                     layer_name: 'y',
                     dim: 1,
                     irange: .005,
                     max_col_norm: 9.9365,
                 }
                ],
        nvis: 117,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 512,
        learning_rate: .01,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_shuffled_sequential',
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:pylearn2.datasets.if_monthly.IFMonthlyLong {
        target_type: 'ASV',
        gain_range: [0, 10],
        which_set: 'test'
                          }
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
             input_include_probs: { 'h0' : .8 },
             input_scales: { 'h0' : 1.25 }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "test_objective",
            prop_decrease: 0.,
            N: 30
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_objective',
             save_path: "IF1503_cut20_raw30x3+ind9x3_ASV10_maxout_100x4-100x4_best.pkl"
        },
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 100,
            final_momentum: .7
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 100,
            decay_factor: .01
        }
    ],
    save_path: "IF1503_cut20_raw30x3+ind9x3_ASV10_maxout_100x4-100x4.pkl",
    save_freq: 1
}
