!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.if_monthly.IFMonthly {
        which_set: 'train',
        hist_len: 1,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 64,
                     irange: .005,
                     max_col_norm: 9.9365,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 64,
                     irange: .005,
                     max_col_norm: 9.9365,
                 },
                 !obj:pylearn2.models.mlp.Linear {
                     layer_name: 'y',
                     dim: 2,
                     irange: .005,
                     max_col_norm: 9.9365,
                 }
                ],
        nvis: 21,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 512,
        learning_rate: .01,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_sequential',
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:pylearn2.datasets.if_monthly.IFMonthly {
                              which_set: 'test',
                              hist_len: 1,
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X'
            }, !obj:pylearn2.costs.mlp.WeightDecay {
                coeffs: [ .00005, .00005, .00005 ]
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "test_term_0",
            prop_decrease: 0.,
            N: 10
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_term_0',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_normXy_best.pkl"
        },
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_normXy.pkl",
    save_freq: 1
}
